### ISSUE TITLE
[BUG] Show government decision disappears in multiplayer

### ISSUE THREAD

**Issue by pingerdactyl** [arkhometha/Historical-Project-Mod#100] opened 2020-01-28 12:56 UTC
**System Information:**
 - Mod Version - v0.4.6 - Hotfix 2
 - Mod Checksum - DOMS

**Describe the bug**
The show government decision disappears for the player that has not selected it when another player has opened it. It will come back when no players has the show show government decision activated.

**To Reproduce**
Have one player open the show government decision and another player check whether the option of showing the government decision has disappeared for them.

**Expected behavior**
Both players have access to the show government decision regardless of whether another player is accessing the options inside it.

**Screenshots**
![Player 1 open](https://user-images.githubusercontent.com/45688791/73265714-6f7e6900-4225-11ea-8776-98b22bb07b07.png)
![Player 2 disappear](https://user-images.githubusercontent.com/45688791/73265769-7c9b5800-4225-11ea-90a5-3170da5fa161.png)
![Player 2 open](https://user-images.githubusercontent.com/45688791/73265790-86bd5680-4225-11ea-8cf7-f15e0e289dc3.png)
![Player 1 disappear](https://user-images.githubusercontent.com/45688791/73265800-8de46480-4225-11ea-8f2c-0fdb95d4b3a6.png)

**Comment by arkhometha** [comment] 2020-02-03 10:05
Hi @pingerdactyl, thanks for the report. That is intended behaviour - meant for players to agree on options and only one of them pick the agreed options. Since options are non-revocable, it would be easy to have chaos if everyone could pick what they want.

**Comment by pingerdactyl** [comment] 2020-02-05 06:53
Hey @arkhometha thanks for responding
I understand it disappearing for the game options but not quite sure why for the government decisions. The problem is that the reform local government, choose trade policy and dissolve upper house are hidden by the show government decision and these decisions only affect the player that enacts them. This becomes a problem because someone wanting to access any of these cannot until whoever is using this closes it even though using these decisions would not affect the other players directly.

**Comment by arkhometha** [comment] 2020-02-05 10:23
Right, that's my bad @pingerdactyl. I misread.
It's fixed and soon enough will be in the stable version.

**Closed as completed** 2020-02-16 23:01 UTC
Labels: bug
