### ISSUE TITLE
[BUG] Game crash always around end of 1885

### ISSUE THREAD

**Issue by pingerdactyl** [arkhometha/Historical-Project-Mod#73] opened 2020-01-18 14:39 UTC
**System Information:**
 - Mod Version - 0.4.6 beta 2
 - Mod Checksum - PETE

**Describe the bug**
The game crashes every time I get to a date somewhere in 1885. But it only crashes if any of the menus are open, you can still play past the date but it will crash if a menu is opened past that particular crash date.

I thought it might be a one off bug so I reloaded to a previous good save but even then the same problem will occur at a very similar date. I also sent my good save to somebody else and they still had the crash problem at the same dates.

Example playing from my save in 1884 it will crash somewhere in 1885 but its a bit random but playing from my save on the 31/8/1885 it crashed exactly on the 9/9/1885 and playing from the save on 19/7/1885 it crashes exactly on 7/9/1885.

My guess would be that an event fired that breaks the game or something similar since its not crashing at the exact date but the closer I save to a crash point the more likely it will crash on an exact date.

**To Reproduce**
Not sure how to produce from 1836 but from my good saves either play past the date then open a menu or open a menu then unpause and once it reaches the date it automatically crashes

**Expected behavior**
Not to crash

**Screenshots**
If applicable, add screenshots to help explain your problem. Save games can also be useful.

[crashing save games.zip](https://github.com/arkhometha/Historical-Project-Mod/files/4080787/crashing.save.games.zip)

**Comment by arkhometha** [comment] 2020-01-19 20:21
Hi @pingerdactyl, thank you very much for the report and especially, for the saves. **I've been able to reproduce the crash consistently**, though not necessarily in the dates you gave me. I have a theory of what is causing it and I'm just confirming if my suspicions are true but things are now looking food since I passed 2 years from the crash date and everything is working.

![image](https://user-images.githubusercontent.com/10909718/72687771-8de7b480-3b01-11ea-8237-f5b259f4e267.png)

I will have more updates soon.

**Comment by arkhometha** [comment] 2020-01-19 22:06
Alright, I understood the problem. The game of the image above crashed, by the way, but I pinpointed the problem to the CSA and the system that cleans ghost units. It was too aggressive and probably because the CSA was a GP and less probably because you were funding their war, either way, the CSA was popping back up to demobilise as soon as it was annexed. The problem occurred in the Diplomacy tab where not enough time had passed for an update and it crashed the game.
For your game @pingerdactyl, I have two files that will fix your problem.

***

**This one goes in your  \Victoria 2\mod\HPM\events**
[CleanUp.txt](https://github.com/arkhometha/Historical-Project-Mod/files/4083701/CleanUp.txt)

***

**This one goes in your \Victoria 2\mod\HPM\decisions**
[CleanUp.txt](https://github.com/arkhometha/Historical-Project-Mod/files/4083703/CleanUp.txt)

***

They have the same name, but they go in different files. **Please don't mix them up.**
I need to test if my fix broke anything with the ghost cleanup system and if everything is alright, I will roll out a commit fixing this and I will close this report. Thanks again for the report!

**Comment by arkhometha** [comment] 2020-01-20 00:03
Fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/c60c9bc277c21544357fc65e2678a53fc3224c57

**Closed as completed by arkhometha** 2020-01-20 00:03 UTC
Labels: bug
