### ISSUE TITLE
[BUG] Netherlands annexation of Beligum diplomacy crash

### ISSUE THREAD

**Issue by freecsu** [arkhometha/Historical-Project-Mod#26] opened 2019-09-07 23:25 UTC
On the latest dev branch there seems to be a bug causing a game crash when opening the diplomacy screen after the Netherlands has restored order to Belgium. I'm not aware of this happening when player Netherlands does this, but it is reproducible as the United Kingdom helping Netherlands restore order to Belgium then opening the diplomacy tab or right-clicking a nation.

EDIT: When loading the save and choosing to play as the Netherlands the problem persists.
This message is visible when the save is loaded as the UK, no idea if it relates to the crash.
![](https://i.imgur.com/prjowqH.png)

**Comment by arkhometha** [comment] 2019-09-09 10:54
Hi and thanks for the report!
I've tried to reproduce the bug using the steps you gave without any success - I wasn't able to reproduce the bug. The decision you see is one of the "cleanup" ones the AI does to guarantee they have the right flags at any given moment. It's harmless.
This sounds like something that would be caused by a bad install (such as an install on version 3.03 or running the mod together with something else, something incompatible), which is why I ask for:
 - Mod Checksum
 - Vanilla Checksum

It helps to know we are on the same page in regards to the game.

![image](https://user-images.githubusercontent.com/10909718/64525019-2e31ff00-d300-11e9-96c8-9a2d17e261f2.png)

![image](https://user-images.githubusercontent.com/10909718/64524772-9207f800-d2ff-11e9-821a-adc7cfec01f5.png)

**Comment by freecsu** [comment] 2019-09-09 14:55
My vanilla checksum is WNVU. My HPM checksum is different than typically because I've changed the RGB values of a few nations in the countries text files. Something I've noticed with HPM is that after playing for some time and then resigning to the main menu the first letter of the checksum will have changed, but returns to normal after a restart. Is that normal behavior?

**Comment by arkhometha** [comment] 2019-09-11 23:04
If I remember correctly, yes, that is normal behaviour. I can't alter anything related to how the game calculates checksum, so it must be.

**Comment by arkhometha** [comment] 2019-09-23 11:27
Well in the absence of anything new, without being able to verify the checksum and unable to reproduce the issue, I need to close this down.

**Closed as completed by arkhometha** 2019-09-23 11:27 UTC
Labels: bug
