### ISSUE TITLE
"Show Organized Colony" decision crashes the game

### ISSUE THREAD

**Issue by alrightjulian** [arkhometha/Historical-Project-Mod#52] opened 2019-12-26 04:40 UTC
As Sweden, when I invoke "Show Organized Colony" decision, the game crashes.
Version: v0.4.6-beta

**Comment by arkhometha** [comment] 2019-12-30 23:38
Hi @julianvargkim, thanks for the report!

I changeownered a few provinces to Sweden (in Nigeria and all the ones in the Gold Coast and the Ivory Coast) to try and reproduce the problem, but I was unsuccessful. Knowing what colonies you had could help in trying to find the cause of the problem. Checksum would also be helpful.

![image](https://user-images.githubusercontent.com/10909718/71604926-8c137c80-2b65-11ea-9def-c9400a30a353.png)

**Comment by arkhometha** [comment] 2020-01-19 19:28
Since there's no more information and I was unable to reproduce the bug, I'm closing this. If it happens again, please, do fill another report - with checksum, so I can verify that everything is in order.

**Closed as completed by arkhometha** 2020-01-19 19:28 UTC
Labels: bug
