### ISSUE TITLE
[BUG] "Take puppet" CB not working

### ISSUE THREAD

**Issue by jobarin94** [arkhometha/Historical-Project-Mod#68] opened 2020-01-13 15:38 UTC
**System Information:**
 - Mod Version: 0.4.6-beta2
 - Mod Checksum; EFDL
 - Vanilla Checksum WNVU

Playing as Japan, 1908, fighting a war against the UK with the "Take Puppet" CB for Australia. When I peace out, the event "The vassalization of Australia" fires. Pressing the button fires the same event again, in a loop ad infinitum. Australia isn't puppeted no matter how many times I press the button. 

![20200113161037_1](https://user-images.githubusercontent.com/59811820/72266986-916dce00-361f-11ea-9ec0-3ebc71b76118.jpg)

Here's a save game, should you need it. You just have to peace out the UK to fire the event. 
[Japan1908_10_02.zip](https://github.com/arkhometha/Historical-Project-Mod/files/4054330/Japan1908_10_02.zip)

P.S: I'm aware my checksum doesn't match. That's an issue I haven't been able to fix, even though I've duly followed every recommendation provided in the pinned bug report. My game seems to run properly, though (save for some very rare crashes), and I don't think this problem be related to the checksum. 

PPS: I love this mod. I'm always checking Github to see if there's anything new. So thank you for your amazing work.

**Comment by arkhometha** [comment] 2020-01-13 21:01
Hey @jobarin94, thanks for taking the time to do this. I've downloaded the save and confirmed it is indeed a problem - one of the events dealing with the new CB was missing (the localization is there, but I have no idea what happened to the event itself). I re-did it and tested in your save and the vassal transfer is working again. This issue is fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/32d615fb9d0081470dad989fadcf252fe3a79200

For you to fix, you can download this file [CleanUp.txt](https://github.com/arkhometha/Historical-Project-Mod/files/4088924/CleanUp.txt) and replace the one in your HPM/events folder with the one you just downloaded. Or wait until I release a new 0.4.6 beta version, which should come soon due to this rather serious bug. All save game compatible. Thanks again for the report!

**Closed as completed by arkhometha** 2020-01-13 21:01 UTC
Labels: bug
