### ISSUE TITLE
[BUG] Incorrect Checksum for 0.4.5.2 and 0.4.6-beta

### ISSUE THREAD

**Issue by Wulfric5** [arkhometha/Historical-Project-Mod#51] opened 2019-12-23 15:16 UTC
**System Information:**
 - Mod Version: 0.4.5.2 and 0.4.6
 - Mod Checksum: LSBY and EOGT
 - Vanilla Checksum: WNVU

**Describe the bug**
For mod versions of 0.4.5.2 and 0.4.6-beta I get the checksums of "LSBY" and "EOGT" respectively while having the vanilla checksum of "WNVU" in both cases. I was able to replicate this issue on two different computers before and after reinstallations of Windows and all the relevant programs. 

Judging by the comments on the ModDB page, many other people seem to have the same checksum of "LSBY" for 0.4.5.2. I was also able to find a few Youtube videos of the mod with the aforementioned checksum. Therefore, this does not seem to be a random occurrence of a corrupted download, etc. 

These were done on the latest Steam version of the game (3.04 non-beta) with verified game files and the aforementioned incorrect checksums appeared after launching the game for the second time.  

Edit: I found a multitude of several similar instances of people getting different checksums for earlier versions of HPM as well, especially on reddit pages of "victoria2" and "paradoxplaza".

**Comment by arkhometha** [comment] 2019-12-30 23:55
Hi @Wulfric5, thanks for the report!

Interesting. I usually mod in a non-steam (GamersGate) version, and that's where I get my checksum from. I've heard of people having trouble putting their mod in the right place and getting it to run in the Steam version, so I have less experience with it...
Anyway, since I'm constantly messing with files, I might as well have changed something in my Vanilla version. I periodically check it and will do it again. For the current version (beta2), I've used a cleam Steam install. Do tell me, if you have the time, if the checksum match.

**Comment by Wulfric5** [comment] 2019-12-31 00:10
For beta2 the checksum is "PETE". So, they still do not match.

**Comment by arkhometha** [comment] 2019-12-31 01:26
Well, a few things to try/keep in mind:
Updating HPM should be done from 0. So delete old HPM folder, unpack new one. The cache in "Documents\Paradox Interactive\Victoria II\HPM" should also be deleted, or at least the "gfx", "logs" and "map" folders. After that, the first time you execute the mod you will have a different, wrong checksum. That's normal. From the second time onwards, the checksum will always remain the same and that's the true checksum. This is all true to Vanilla too, so deleting the "vanilla game" checksum will exhibit the same behaviour.

If all of this is being done (and since you mention a "second time in your post, I believe it is being done") and observed and the checksum still doesn't match, the mod could be being run together with another mod. Or something is corrupting the V2/HPM files/downloads.

I just checked my GG version of Victoria 2 and the checksum is SUWT. Steam and non-steam version have the same vanilla checksum, but modded they change the checksum. Which is weird but not unexpected from the weird behaviour I've heard reported with the Steam version.

That basically is all I can do: advise you on what to do to test and try to get the same checksum. People will always get different checksums - some people unpack new versions on top of old ones, some files sometimes get corrupted in vanilla and Steam needs to verify things, some people install the mode on top of a 3.03 installation or even install it without Heart of Darkness or A House Divided. So it's hard to gauge how many people are getting it wrong or what is happening that there's a mismatch.

The very last thing I can think of are the less known DLCs. There's 2 DLCs for unit skins (one for the American Civil War, one for the Great War, IIRC) and there's one DLC with music. That was old GG stuff - I don't think the music one even exists in Steam. They would not affect the Checksum, theoretically, but just to be sure: My Steam version of the game, were I got the Checksum, has no DLC besides A house divided and a heart of darkness. My GG version I think has the 2 unit skin DLCs but not the music DLC. I'm not sure these minor DLCs affect the checksum but it's worth a shot. If all fail, sorry, but that's as far as I can try to help you.

**Comment by pingerdactyl** [comment] 2019-12-31 02:53
Hey, I also got the same PETE checksum with the beta 2 update not sure why though either

**Comment by arkhometha** [comment] 2019-12-31 16:26
Thansk for the info @pingerdactyl. I'm beginning to think the problem is either on my side or it is related to the DLC. I will try and explore the possibilities a bit more.

**Comment by hartz8001** [comment] 2020-01-04 02:29
I also got the PETE checksum if it helps. I downloaded the game from Steam

**Comment by arkhometha** [comment] 2020-01-17 01:17
It helps, @tintin8001. The more confirmation, the more likely the problem is on my side.

I reinstalled everything and finally got PETE as the checksum for the Steam version. The non-steam version, which had problems in the vanilla files, is ILFB. I updated the release post to reflect this. I would like independent verification on the non-steam version checksum, and I still find the phenomenon of different mod checksums in different game versions despite them having the same vanilla checksum, but I can't do anything about that, I guess.

![image](https://user-images.githubusercontent.com/10909718/72576180-c9e30580-38c6-11ea-9557-10032c6059e5.png)

I got the right checksum after deleting the cache, reinstalling everything and double-checking everything. I will be a bit more systematic in the future in regards to the checksum - deleting caches before checking them, which will hopefully avoid the problem in the future.

**Comment by arkhometha** [comment] 2020-01-21 15:34
Now with the non-beta 0.4.6 released, I'd like someone to confirm the checksum so I can close this issue.

**Comment by hartz8001** [comment] 2020-01-22 03:29
In the 0.4.6.1 version I have KAQP, the same as your checksum.

**Comment by arkhometha** [comment] 2020-01-22 14:44
Thanks @tintin8001, I also got a confirmation that the 0.4.6 release had the right checksum. I assume everything is right now. From now on I will keep a separate installation to guarantee the right checksum when releasing.

**Closed as completed by arkhometha** 2020-01-22 14:44 UTC
Labels: bug
